from django.urls import path
from tea_supply.views import (
    cancel_order,
    boss_dashboard,
    boss_start_delivery,
    checkout_submit_order,
    confirm_order,
    credit_apply_view,
    credit_home_view,
    demo_landing,
    driver_orders,
    inventory_list,
    login_view,
    mark_order_paid,
    my_orders_view,
    order_status_update,
    orders_list,
    profile_view,
    customer_insights_dashboard,
    reports_dashboard,
    replenishment_dashboard,
    bank_transfer_instructions,
    logout_view,
    mark_order_payment_failed,
    shop_checkout,
    shop_home,
    shop_login,
    shop_logout,
    shop_orders,
    shop_order_success,
    shop_product_detail,
    shop_submit_order,
    stripe_cancel,
    stripe_create_session,
    stripe_success,
    update_transfer_reference,
    wholesale_order_entry,
)

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", boss_dashboard, name="boss-dashboard"),
    path("dashboard/order/<int:order_id>/start-delivery/", boss_start_delivery, name="boss-start-delivery"),
    path("profile/", profile_view, name="profile"),
    path("my-orders/", my_orders_view, name="my-orders"),
    path("credit/", credit_home_view, name="credit-home"),
    path("credit/apply/", credit_apply_view, name="credit-apply"),
    path("demo/", demo_landing, name="demo-landing"),
    path("shop/", shop_home, name="shop-home"),
    path("shop/login/", shop_login, name="shop-login"),
    path("shop/logout/", shop_logout, name="shop-logout"),
    path("shop/checkout/", shop_checkout, name="shop-checkout"),
    path("checkout/", shop_checkout, name="checkout"),
    path("checkout/submit/", checkout_submit_order, name="checkout-submit"),
    path("shop/orders/", shop_orders, name="shop-orders"),
    path("shop/product/<int:product_id>/", shop_product_detail, name="shop-product-detail"),
    path("shop/order/", shop_submit_order, name="shop-submit-order"),
    path("shop/submit-order/", shop_submit_order, name="shop-submit-order-legacy"),
    path("shop/order/success/<int:order_id>/", shop_order_success, name="shop-order-success"),
    path("payments/stripe/create-session/<int:order_id>/", stripe_create_session, name="stripe-create-session"),
    path("payments/stripe/success/", stripe_success, name="stripe-success"),
    path("payments/stripe/cancel/", stripe_cancel, name="stripe-cancel"),
    path(
        "payments/bank-transfer/<int:order_id>/",
        bank_transfer_instructions,
        name="bank-transfer-instructions",
    ),
    path(
        "payments/bank-transfer/<int:order_id>/reference/",
        update_transfer_reference,
        name="update-transfer-reference",
    ),
    path("", wholesale_order_entry, name="wholesale-order-entry"),
    path("inventory/", inventory_list, name="inventory-list"),
    path("replenishment/", replenishment_dashboard, name="replenishment-dashboard"),
    path("reports/", reports_dashboard, name="reports-dashboard"),
    path("reports/customers/", customer_insights_dashboard, name="reports-customers"),
    path("orders/", orders_list, name="orders-list"),
    path("order/<int:order_id>/paid/", mark_order_paid, name="order_paid"),
    path("order/<int:order_id>/payment-failed/", mark_order_payment_failed, name="order-payment-failed"),
    path("order/<int:order_id>/confirm/", confirm_order, name="order-confirm"),
    path("order/<int:order_id>/cancel/", cancel_order, name="order-cancel"),
    path("orders/<int:order_id>/status/", order_status_update, name="order-status-update"),
    path("driver/orders/", driver_orders, name="driver-orders"),
]