# Generated by Django 4.2.29 on 2026-03-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='原材料名称')),
                ('stock', models.FloatField(default=0, verbose_name='当前库存')),
                ('unit', models.CharField(max_length=20, verbose_name='单位（kg / L / 个）')),
                ('warning_level', models.FloatField(default=0, verbose_name='预警值')),
            ],
        ),
    ]
