# Generated by Django 4.2.29 on 2026-03-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0003_alter_order_created_at_alter_order_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('delivery_zone', models.CharField(max_length=100, verbose_name='配送区域')),
                ('is_monthly_settlement', models.BooleanField(default=False, verbose_name='是否月结')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('待处理', '待处理'), ('已确认', '已确认'), ('已配货', '已配货'), ('已发货', '已发货'), ('已完成', '已完成'), ('已取消', '已取消')], default='待处理', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tea_supply.customer', verbose_name='客户'),
        ),
    ]
