# Generated by Django 4.2.29 on 2026-03-20 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0004_customer_order_status_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tea_supply.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='批发订单', max_length=100, verbose_name='订单名称'),
        ),
    ]
