# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tea_supply", "0005_ingredient_price_alter_order_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_level",
            field=models.CharField(
                choices=[
                    ("普通客户", "普通客户"),
                    ("VIP客户", "VIP客户"),
                    ("月结客户", "月结客户"),
                    ("核心客户", "核心客户"),
                ],
                default="普通客户",
                max_length=20,
                verbose_name="客户等级",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="allow_credit",
            field=models.BooleanField(default=False, verbose_name="是否允许欠款"),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.FloatField(default=0, verbose_name="信用额度"),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_cycle",
            field=models.CharField(
                choices=[
                    ("现结", "现结"),
                    ("周结", "周结"),
                    ("半月结", "半月结"),
                    ("月结", "月结"),
                ],
                default="现结",
                max_length=20,
                verbose_name="结算周期",
            ),
        ),
    ]
