# Generated by Django 4.2.29 on 2026-03-21 00:33

from django.db import migrations, models


def forwards_recompute_tier_limits(apps, schema_editor):
    Customer = apps.get_model("tea_supply", "Customer")
    OrderItem = apps.get_model("tea_supply", "OrderItem")
    Ingredient = apps.get_model("tea_supply", "Ingredient")
    for cust in Customer.objects.all():
        total = 0.0
        for oi in OrderItem.objects.filter(order__customer_id=cust.pk):
            ing = Ingredient.objects.get(pk=oi.ingredient_id)
            total += float(oi.quantity) * float(ing.price)
        if total < 200:
            level, allow, credit = "C", False, 0.0
        elif total < 500:
            level, allow, credit = "B", True, 100.0
        elif total < 1000:
            level, allow, credit = "A", True, 500.0
        else:
            level, allow, credit = "VIP", True, 2000.0
        Customer.objects.filter(pk=cust.pk).update(
            customer_level=level,
            allow_credit=allow,
            credit_limit=credit,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0008_customer_level_c_b_a_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='allow_credit',
            field=models.BooleanField(default=False, help_text='与等级联动自动更新；录单/结算后系统会按规则覆盖手动修改。', verbose_name='是否允许欠款'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.FloatField(default=0, help_text='与等级联动自动更新（如 B=100、A=500、VIP=2000）；录单/结算后会覆盖手动修改。', verbose_name='信用额度'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('VIP', 'VIP')], default='C', help_text='按历史累计消费自动划分（C/B/A/VIP）。保存订单、结算、变更明细后会重新计算并覆盖手动修改。', max_length=10, verbose_name='客户等级'),
        ),
        migrations.RunPython(forwards_recompute_tier_limits, migrations.RunPython.noop),
    ]
