# Generated by Django 4.2.29 on 2026-03-21 00:47

from django.db import migrations, models


def backfill_order_totals(apps, schema_editor):
    Order = apps.get_model("tea_supply", "Order")
    OrderItem = apps.get_model("tea_supply", "OrderItem")
    for order in Order.objects.all().iterator():
        total_revenue = 0.0
        total_cost = 0.0
        for item in OrderItem.objects.filter(order_id=order.pk).select_related("ingredient"):
            q = float(item.quantity)
            total_revenue += q * float(item.ingredient.price)
            total_cost += q * float(item.ingredient.cost_price)
        profit = total_revenue - total_cost
        Order.objects.filter(pk=order.pk).update(
            total_revenue=total_revenue,
            total_cost=total_cost,
            profit=profit,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0009_customer_tier_help_and_recompute'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_price',
            field=models.FloatField(default=0, verbose_name='成本价'),
        ),
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.FloatField(default=0, verbose_name='利润'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0, verbose_name='总成本'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_revenue',
            field=models.FloatField(default=0, verbose_name='总收入'),
        ),
        migrations.RunPython(backfill_order_totals, migrations.RunPython.noop),
    ]
