# Generated by Django 4.2.29 on 2026-03-21 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0011_product_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='可选；关联后按单品数量或整箱×每箱扣减数扣库存。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea_supply.ingredient', verbose_name='关联原材料（库存扣减）'),
        ),
    ]
