# Generated by Django 4.2.29 on 2026-03-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0012_alter_orderitem_quantity_alter_product_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pricing_note',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='折扣来源'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='成交单价'),
        ),
        migrations.CreateModel(
            name='CustomerProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price_single', models.FloatField(default=0, verbose_name='专属单品价')),
                ('custom_price_case', models.FloatField(default=0, verbose_name='专属整箱价')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='tea_supply.customer', verbose_name='客户')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='tea_supply.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '客户商品专属价',
                'verbose_name_plural': '客户商品专属价',
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
