# Generated by Django 4.2.29 on 2026-03-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0013_customer_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default='', help_text='相对 MEDIA_ROOT 的路径，如 products/T010103.png；由目录 PDF 导入时写入。', max_length=500, verbose_name='商品主图'),
        ),
    ]
