# Generated by Django 4.2.29 on 2026-03-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0018_stocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('disabled', '已禁用')], default='approved', help_text='仅「已通过」可在商城下单；新手机号自助注册为待审核。', max_length=16, verbose_name='商城账号状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('VIP', 'VIP')], default='C', help_text='商城/录单：专属价优先；仅 VIP 享 9 折，其余等级按原价。可在此手动改等级；订单也会按消费自动重算等级。', max_length=10, verbose_name='客户等级（VIP）'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text='进入「备货中」时扣减；取消或退回待确认时恢复。勿手动改，除非清楚含义。', verbose_name='已扣库存'),
        ),
    ]
