# Generated by Django 4.2.29 on 2026-03-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0020_product_price_on_request_catalog_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_session_key',
            field=models.CharField(blank=True, default='', help_text='未登录商城下单时写入 session key，用于成功页校验；已登录客户订单为空。', max_length=40, verbose_name='游客会话标识'),
        ),
        migrations.AlterField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('pending_confirm', '待确认'), ('confirmed', '已确认'), ('preparing', '备货中'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending_confirm', max_length=24, verbose_name='履约状态'),
        ),
    ]
