# Generated by Django 4.2.29 on 2026-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0021_order_guest_session_and_confirmed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='与履约状态配合使用；新单默认未确认。', verbose_name='商家已确认'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='数量'),
        ),
    ]
