# Generated by Django 4.2.29 on 2026-03-23 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_bind_customer_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Customer = apps.get_model("tea_supply", "Customer")
    UserRole = apps.get_model("tea_supply", "UserRole")

    # 先给现有 Django 用户补角色
    for u in User.objects.all():
        if u.is_superuser:
            role = "owner"
        elif u.is_staff:
            role = "staff"
        else:
            role = "customer"
        UserRole.objects.get_or_create(user=u, defaults={"role": role})

    # 将 Customer 绑定到 User。优先手机号；没有则创建新用户。
    for c in Customer.objects.filter(user__isnull=True):
        phone = (c.phone or "").strip()
        hit = None
        if phone:
            hit = User.objects.filter(username=phone).first()
        if hit is None and phone:
            hit = User.objects.filter(email=phone).first()
        if hit is not None:
            occupied = Customer.objects.filter(user_id=hit.id).exclude(pk=c.pk).exists()
            if occupied:
                hit = None
        if hit is None:
            base = phone if phone else f"customer{c.pk}"
            username = base
            idx = 1
            while User.objects.filter(username=username).exists():
                idx += 1
                username = f"{base}_{idx}"
            hit = User.objects.create(
                username=username,
                first_name=(c.name or "")[:150],
                is_active=True,
                is_staff=False,
                is_superuser=False,
            )
            hit.password = "!"
            hit.save(update_fields=["password"])
        c.user_id = hit.id
        c.save(update_fields=["user"])
        UserRole.objects.update_or_create(user=hit, defaults={"role": "customer"})


def backward_bind_customer_users(apps, schema_editor):
    Customer = apps.get_model("tea_supply", "Customer")
    Customer.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tea_supply', '0022_order_confirmed_item_qty_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='统一账号体系：客户使用 Django User 登录商城。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='登录账号'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '老板'), ('staff', '员工'), ('customer', '客户')], default='customer', max_length=16, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.RunPython(forward_bind_customer_users, backward_bind_customer_users),
    ]
