# Generated by Django 4.2.29 on 2026-03-23 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_fill_ordered_by(apps, schema_editor):
    Order = apps.get_model("tea_supply", "Order")
    for o in Order.objects.filter(ordered_by__isnull=True).exclude(customer__user__isnull=True):
        o.ordered_by_id = o.customer.user_id
        o.save(update_fields=["ordered_by"])


def backward_clear_ordered_by(apps, schema_editor):
    Order = apps.get_model("tea_supply", "Order")
    Order.objects.all().update(ordered_by=None)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tea_supply', '0023_unify_user_roles_and_customer_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(blank=True, help_text='提交订单时绑定 request.user（客户前台/员工录单）。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='下单用户'),
        ),
        migrations.RunPython(forward_fill_ordered_by, backward_clear_ordered_by),
    ]
