# Generated by Django 4.2.29 on 2026-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0024_bind_order_to_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='店名'),
        ),
    ]
