# Generated by Django 4.2.29 on 2026-03-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0025_add_customer_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='settlement_type',
            field=models.CharField(choices=[('cash', '现结'), ('credit', '挂账')], default='cash', help_text='cash=现结；credit=挂账（需客户开通赊账且不超额度）。', max_length=12, verbose_name='结算方式'),
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, default='', max_length=200, verbose_name='店名')),
                ('contact_name', models.CharField(blank=True, default='', max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='手机号')),
                ('monthly_purchase_estimate', models.FloatField(default=0, verbose_name='月采购额预估')),
                ('requested_credit_limit', models.FloatField(default=0, verbose_name='申请额度')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=12, verbose_name='审核状态')),
                ('approved_credit_limit', models.FloatField(default=0, verbose_name='审批额度')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='审批备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='tea_supply.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '信用额度申请',
                'verbose_name_plural': '信用额度申请',
                'ordering': ('-created_at',),
            },
        ),
    ]
