# Generated by Django 4.2.29 on 2026-03-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0026_credit_application_and_settlement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_debt',
            field=models.FloatField(default=0, help_text='挂账订单累计未收款金额；收款后自动减少，不低于 0。', verbose_name='当前欠款'),
        ),
    ]
