# Generated by Django 4.2.29 on 2026-03-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0027_add_customer_current_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_debt_counted',
            field=models.BooleanField(default=False, help_text='挂账订单进入已确认后计入欠款；用于防止重复累计。', verbose_name='欠款已计入'),
        ),
    ]
