# Generated by Django 4.2.29 on 2026-03-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0028_order_debt_counted_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.FloatField(default=0, verbose_name='成交单位成本'),
        ),
    ]
