# Generated by Django 4.2.29 on 2026-03-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0029_orderitem_unit_cost_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', '信用卡/借记卡'), ('bank_transfer', '银行转账')], default='stripe', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('failed', '支付失败'), ('pending_transfer', '待转账确认')], default='unpaid', max_length=24, verbose_name='支付状态'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Session ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='转账参考号'),
        ),
    ]
