# Generated by Django 4.2.29 on 2026-03-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0030_add_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='可与客户名称不同；前台可自助修改。', max_length=100, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='关闭后该客户无法在商城下单（与「商城账号状态」独立，供运营停用档案）。', verbose_name='客户档案启用'),
        ),
        migrations.AddField(
            model_name='customer',
            name='minimum_order_amount',
            field=models.FloatField(default=0, help_text='商城/录单起送门槛（元）；0 表示不设门槛。', verbose_name='起送金额'),
        ),
    ]
