# Generated by Django 4.2.29 on 2026-03-24 01:09

from django.db import migrations, models


def seed_level_rules(apps, schema_editor):
    Rule = apps.get_model("tea_supply", "CustomerLevelPriceRule")
    defaults = [
        ("C", 1.0, 1.0),
        ("B", 0.95, 0.95),
        ("A", 0.90, 0.90),
        ("VIP", 0.90, 0.90),
    ]
    for lvl, s, c in defaults:
        Rule.objects.update_or_create(
            level=lvl,
            defaults={
                "single_discount_rate": s,
                "case_discount_rate": c,
                "is_active": True,
            },
        )


def seed_level_rules_reverse(apps, schema_editor):
    Rule = apps.get_model("tea_supply", "CustomerLevelPriceRule")
    Rule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0031_customer_contact_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevelPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('VIP', 'VIP')], max_length=10, unique=True, verbose_name='等级')),
                ('single_discount_rate', models.FloatField(default=1.0, help_text='成交价 = 单品基础价 × 本系数；1.0 为原价。', verbose_name='单品折扣率')),
                ('case_discount_rate', models.FloatField(default=1.0, help_text='成交价 = 整箱基础价 × 本系数；1.0 为原价。', verbose_name='整箱折扣率')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '等级折扣规则',
                'verbose_name_plural': '等级折扣规则',
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('VIP', 'VIP')], default='C', help_text='商城/录单：专属价优先；否则按「等级折扣规则」表对基础价打折。可手动改等级；订单也会按消费自动重算等级。', max_length=10, verbose_name='客户等级（VIP）'),
        ),
        migrations.RunPython(seed_level_rules, seed_level_rules_reverse),
    ]
