# Generated by Django 4.2.29 on 2026-03-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0032_customer_level_price_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('VIP', 'VIP')], default='C', help_text='商城/录单：专属价优先；否则按统一等级折扣（VIP×0.90、A×0.95、B×0.98、C×1.00）乘基础价。可手动改等级；订单也会按消费自动重算等级。', max_length=10, verbose_name='客户等级（VIP）'),
        ),
    ]
