# Generated by Django 4.2.29 on 2026-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0033_alter_customer_level_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', '银行转账'), ('check', '支票'), ('card_on_pickup', '现场刷卡/取货付款'), ('cash', '现金'), ('credit', '挂账')], default='bank_transfer', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未支付'), ('pending_confirmation', '待确认'), ('paid', '已支付'), ('partial', '部分付款'), ('cancelled', '已取消')], default='unpaid', max_length=24, verbose_name='支付状态'),
        ),
    ]
