# Generated by Django 4.2.29 on 2026-03-24 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0035_backfill_order_payment_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.FloatField(default=100, help_text='稳版统一库存（默认假库存 100），用于商城下单校验与扣减。', verbose_name='当前库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='safety_stock',
            field=models.FloatField(default=10, help_text='低于或等于该值时前台显示低库存提醒。', verbose_name='安全库存'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_enabled',
            field=models.BooleanField(default=True, help_text='关闭后允许忽略库存校验继续下单。', verbose_name='启用库存校验'),
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('in', '入库'), ('out', '出库'), ('adjust', '调整')], max_length=12, verbose_name='变动类型')),
                ('quantity', models.FloatField(default=0, verbose_name='变动数量')),
                ('before_stock', models.FloatField(default=0, verbose_name='变动前库存')),
                ('after_stock', models.FloatField(default=0, verbose_name='变动后库存')),
                ('note', models.CharField(blank=True, default='', max_length=240, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='tea_supply.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存流水（稳版）',
                'verbose_name_plural': '库存流水（稳版）',
                'ordering': ('-created_at',),
            },
        ),
    ]
