# Generated by Django 4.2.29 on 2026-03-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0036_product_current_stock_product_safety_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_logs', to='tea_supply.order', verbose_name='关联订单'),
        ),
    ]
