# Generated by Django 4.2.29 on 2026-03-24 04:10

from django.db import migrations, models


def _backfill_blocked(apps, schema_editor):
    Customer = apps.get_model("tea_supply", "Customer")
    for c in Customer.objects.all().only("id", "credit_limit", "current_debt", "is_blocked"):
        limit = float(c.credit_limit or 0)
        debt = float(c.current_debt or 0)
        if limit > 0 and debt >= limit and not c.is_blocked:
            Customer.objects.filter(pk=c.pk).update(is_blocked=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0037_inventorylog_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='欠款≥信用额度时系统自动停单；后台可手动解除（欠款与额度未变时保留解除状态）。', verbose_name='是否停单'),
        ),
        migrations.RunPython(_backfill_blocked, migrations.RunPython.noop),
    ]
