# Generated by Django 4.2.29 on 2026-03-25 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tea_supply', '0039_normalize_product_category_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('plate_number', models.CharField(blank=True, default='', max_length=32, verbose_name='车牌')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='载量')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '配送车辆',
                'verbose_name_plural': '配送车辆',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to=settings.AUTH_USER_MODEL, verbose_name='配送司机'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='配送日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', verbose_name='配送备注'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Delivering', 'Delivering'), ('Completed', 'Completed')], default='Pending', max_length=20, verbose_name='配送状态'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_level',
            field=models.CharField(choices=[('C', 'C'), ('B', 'B'), ('A', 'A'), ('VIP', 'VIP')], default='C', help_text='商城/录单：专属价优先；否则按统一等级折扣（VIP×0.85、A×0.90、B×0.95、C×1.00）乘基础价。可手动改等级；订单也会按消费自动重算等级。', max_length=10, verbose_name='客户等级（VIP）'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Wholesale order', max_length=100, verbose_name='订单名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('check', 'Check'), ('card_on_pickup', 'Card on pickup'), ('cash', 'Cash'), ('credit', 'On account')], default='bank_transfer', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_confirmation', 'Pending confirmation'), ('paid', 'Paid'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='unpaid', max_length=24, verbose_name='支付状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='settlement_type',
            field=models.CharField(choices=[('cash', 'Cash terms'), ('credit', 'On account')], default='cash', help_text='cash=现结；credit=挂账（需客户开通赊账且不超额度）。', max_length=12, verbose_name='结算方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Settled')], default='pending', max_length=20, verbose_name='结算状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='workflow_status',
            field=models.CharField(choices=[('pending_confirm', 'Pending confirm'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirm', max_length=24, verbose_name='履约状态'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sale_type',
            field=models.CharField(choices=[('single', 'Single'), ('case', 'Case')], default='single', max_length=10, verbose_name='销售方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tea_supply.vehicle', verbose_name='分配车辆'),
        ),
    ]
