# Generated by Django 4.2.29 on 2026-03-25 05:10

from django.conf import settings
from django.db import migrations


def clean_delivery_status_values(apps, schema_editor):
    Order = apps.get_model("tea_supply", "Order")

    # Map historical values (Chinese / old enum display values) -> current choices keys.
    mapping = {
        "待处理的": "pending",
        "待处理": "pending",
        "待配送": "pending",
        "Pending": "pending",
        "Assigned": "assigned",
        "Delivering": "delivering",
        "Completed": "completed",
        "已完成": "completed",
    }

    # Perform updates as individual bulk UPDATEs for simplicity.
    for old_value, new_value in mapping.items():
        Order.objects.filter(delivery_status=old_value).update(delivery_status=new_value)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tea_supply", "0041_order_delivery_fields_update"),
    ]

    operations = [
        migrations.RunPython(clean_delivery_status_values, migrations.RunPython.noop),
    ]

