# Generated by Django 4.2.29 on 2026-03-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0042_clean_delivery_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0, help_text='供应链库存（V1）：订单确认/收款后扣减；用于库存预警与补货。', verbose_name='当前库存（供应链）'),
        ),
        migrations.AlterField(
            model_name='product',
            name='safety_stock',
            field=models.FloatField(default=20, help_text='低于或等于该值时前台显示低库存提醒。', verbose_name='安全库存'),
        ),
    ]
