# Generated by Django 4.2.29 on 2026-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0043_inventory_stock_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_daily_sales',
            field=models.FloatField(default=0, help_text='补货建议（V1）：用于估算 lead time 期间需求量。', verbose_name='平均日销量'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='补货建议（V1）：从下单到到货的周期天数。', verbose_name='补货周期（天）'),
        ),
    ]
