# Generated by Django 4.2.29 on 2026-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0044_reorder_suggestion_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_rate',
            field=models.FloatField(default=1.0, help_text='动态定价（V1）：成交价 = 原价 × 折扣系数。', verbose_name='折扣'),
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('NORMAL', 'NORMAL'), ('VIP', 'VIP'), ('PREMIUM', 'PREMIUM')], default='NORMAL', help_text='动态定价（V1）：NORMAL/VIP/PREMIUM。', max_length=16, verbose_name='等级'),
        ),
    ]
