# Generated by Django 4.2.29 on 2026-03-25 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def bootstrap_default_company(apps, schema_editor):
    Company = apps.get_model("tea_supply", "Company")
    UserCompanyProfile = apps.get_model("tea_supply", "UserCompanyProfile")
    Customer = apps.get_model("tea_supply", "Customer")
    Product = apps.get_model("tea_supply", "Product")
    Order = apps.get_model("tea_supply", "Order")
    InventoryLog = apps.get_model("tea_supply", "InventoryLog")
    StockLog = apps.get_model("tea_supply", "StockLog")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    owner = (
        User.objects.filter(is_superuser=True).order_by("id").first()
        or User.objects.filter(is_staff=True).order_by("id").first()
        or User.objects.order_by("id").first()
    )
    default_company, _ = Company.objects.get_or_create(
        name="Default Company", defaults={"owner_id": getattr(owner, "id", None)}
    )

    # Ensure every user has a company profile.
    for u in User.objects.all().only("id"):
        UserCompanyProfile.objects.get_or_create(
            user_id=u.id, defaults={"company_id": default_company.id}
        )

    # Assign company to core data (existing single-tenant data -> default company).
    Customer.objects.filter(company__isnull=True).update(company_id=default_company.id)
    Product.objects.filter(company__isnull=True).update(company_id=default_company.id)
    Order.objects.filter(company__isnull=True).update(company_id=default_company.id)
    InventoryLog.objects.filter(company__isnull=True).update(company_id=default_company.id)
    StockLog.objects.filter(company__isnull=True).update(company_id=default_company.id)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tea_supply', '0045_customer_tier_pricing_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tea_supply.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户公司绑定',
                'verbose_name_plural': '用户公司绑定',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tea_supply.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='tea_supply.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tea_supply.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tea_supply.company', verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='tea_supply.company', verbose_name='公司'),
        ),
        migrations.RunPython(bootstrap_default_company, migrations.RunPython.noop),
    ]
