# Generated by GPT-5.2 on 2026-03-25

from django.db import migrations


def _column_names(schema_editor, table_name: str):
    with schema_editor.connection.cursor() as cursor:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table_name)
    names = []
    for c in desc:
        n = getattr(c, "name", None) or getattr(c, "column_name", None)
        if n:
            names.append(str(n))
    return set(names)


def ensure_customer_level_columns(apps, schema_editor):
    Customer = apps.get_model("tea_supply", "Customer")
    table = Customer._meta.db_table
    cols = _column_names(schema_editor, table)

    to_ensure = ["level", "discount_rate"]
    for field_name in to_ensure:
        if field_name in cols:
            continue
        field = Customer._meta.get_field(field_name)
        schema_editor.add_field(Customer, field)
        cols.add(field_name)


class Migration(migrations.Migration):
    dependencies = [
        ("tea_supply", "0046_multi_tenant_saas_v1"),
    ]

    operations = [
        migrations.RunPython(ensure_customer_level_columns, migrations.RunPython.noop),
    ]

