# Generated by Django 4.2.29 on 2026-03-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_supply', '0049_order_status_flow_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('check', 'Check'), ('card_on_pickup', 'Card on pickup'), ('cash', 'Cash'), ('credit', 'On account'), ('stripe', 'Stripe')], default='bank_transfer', max_length=20, verbose_name='支付方式'),
        ),
    ]
