"""
Django settings for tea_supply project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# ---- 环境变量（Railway / 生产部署）----
# DJANGO_SECRET_KEY：强烈建议设置；未设置时仍可启动（见下方兜底，仅便于首次部署）
# DJANGO_DEBUG：未设置时：本地默认 True；检测到 Railway 环境时默认 False
# ALLOWED_HOSTS：固定为 *（Railway 临时域名 / 部署兼容性；上线后可在平台侧限制访问）


def _env_bool(name: str, default: bool) -> bool:
    v = os.environ.get(name)
    if v is None:
        return default
    return str(v).strip().lower() in ("1", "true", "yes", "on")


# Railway 通常提供 RAILWAY_ENVIRONMENT；Render 提供 RENDER / RENDER_EXTERNAL_URL
_on_railway = bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))
_on_render = bool(os.environ.get("RENDER") or os.environ.get("RENDER_EXTERNAL_URL"))
# 优先读环境变量 DEBUG（与常见 PaaS 一致）；未设置时再回退 DJANGO_DEBUG / 平台默认
if "DEBUG" in os.environ:
    DEBUG = os.environ.get("DEBUG", "False").lower() == "true"
else:
    DEBUG = _env_bool("DJANGO_DEBUG", default=False if (_on_railway or _on_render) else True)

# 生产环境将 500 等错误打到 stderr，便于 Render / 容器日志查看 traceback
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {"handlers": ["console"], "level": "INFO"},
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        # 本地开发默认 key（切勿用于生产）
        SECRET_KEY = "django-insecure-$5m7-x87f2saqy35--zh-j0@b*n)&680%8o*uu1jbeg@@)#0^k"
    else:
        # 生产未设置密钥时仍可启动（避免首部署因缺变量崩溃）；上线后请在面板设置 DJANGO_SECRET_KEY
        SECRET_KEY = (
            "django-insecure-RAILWAY-UNSET-SECRET-KEY-PLEASE-SET-DJANGO_SECRET_KEY-IN-DASHBOARD"
        )

ALLOWED_HOSTS = ["*"]

# ---- CSRF / HTTPS（Render / Railway / 反向代理）----
# Django 4.x 在 HTTPS 下会校验 Origin/Referer；生产若未配置会导致
# 「CSRF token from POST incorrect」或 403。
# Render 提供 RENDER_EXTERNAL_URL（如 https://xxx.onrender.com）；也可在面板设置 CSRF_TRUSTED_ORIGINS（逗号分隔）。
def _parse_csrf_trusted_origins():
    raw = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
    out = []
    for part in raw.split(","):
        p = part.strip()
        if p:
            out.append(p.rstrip("/"))
    render_url = os.environ.get("RENDER_EXTERNAL_URL", "").strip()
    if render_url:
        u = render_url.rstrip("/")
        if u not in out:
            out.append(u)
    railway_public = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "").strip()
    if railway_public:
        u = railway_public
        if not u.startswith("http"):
            u = "https://" + u
        u = u.rstrip("/")
        if u not in out:
            out.append(u)
    # 去重且保持顺序
    seen = set()
    uniq = []
    for o in out:
        if o not in seen:
            seen.add(o)
            uniq.append(o)
    return uniq


CSRF_TRUSTED_ORIGINS = _parse_csrf_trusted_origins()

# 终止 TLS 的反向代理（Render / nginx）会把原始协议放在 X-Forwarded-Proto
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# 生产环境在 HTTPS 下使用安全 Cookie（与 CSRF 校验一致）
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'tea_supply.apps.TeaSupplyConfig',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tea_supply.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tea_supply.context_processors.currency',
                'tea_supply.context_processors.portal_rbac',
            ],
        },
    },
]

WSGI_APPLICATION = 'tea_supply.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# 本地：SQLite；Render 等：环境变量 DATABASE_URL（PostgreSQL）

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic 输出目录（生产部署用；勿提交到 git，见 .gitignore）
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_ROOT.mkdir(parents=True, exist_ok=True)

# 生产环境使用 WhiteNoise 压缩；部署请用 gunicorn（见根目录 Procfile）
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# 未执行 collectstatic 时，DEBUG 下仍可从 STATICFILES_DIRS 找静态文件
WHITENOISE_USE_FINDERS = DEBUG

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# 商城商品无图时前台使用（STATICFILES_DIRS 下 static/images/default.png）
DEFAULT_PRODUCT_IMAGE_STATIC = "images/default.png"

# 询价条 / 联系下单（可选，用于「联系下单 / Contact Us」链接）
SHOP_CONTACT_PHONE = os.environ.get("SHOP_CONTACT_PHONE", "").strip()
SHOP_CONTACT_HINT = (
    os.environ.get("SHOP_CONTACT_HINT", "").strip()
    or "请联系业务员或致电门店确认价格与下单（Contact us to order）。"
)

CURRENCY_SYMBOL = os.environ.get("CURRENCY_SYMBOL", "$").strip() or "$"

# Payment (Stripe / Bank Transfer)
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "").strip()
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "").strip()
BANK_NAME = os.environ.get("BANK_NAME", "").strip()
BANK_ACCOUNT_NAME = os.environ.get("BANK_ACCOUNT_NAME", "").strip()
BANK_ACCOUNT_NUMBER = os.environ.get("BANK_ACCOUNT_NUMBER", "").strip()
BANK_ROUTING_NUMBER = os.environ.get("BANK_ROUTING_NUMBER", "").strip()
BANK_TRANSFER_INFO = {
    "bank_name": "Chase Bank",
    "account_name": "Yancy Supply LLC",
    "account_number": "123456789",
    "routing_number": "021000021",
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth redirect for the backend pages
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
